### ISSUE TITLE
Possible to support German language?

### ISSUE THREAD

**Issue by GeorgeS2019** [kaiidams/NeMoOnnxSharp#20]
Possible to support German language

**Comment by kaiidams** [comment]
NeMo provides German models. Writing phonemizers/tokenizers for German should not be difficult.

**Comment by GeorgeS2019** [comment]
@kaiidams 
I went through NeMo, I could not find how German is supported. Any link would really appreciate.

**Comment by kaiidams** [comment]
This page lists available models https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/tts/checkpoints.html

If you have NeMo installed. You can run 
```py
from nemo.collections.tts.models.base import SpectrogramGenerator, Vocoder
from nemo.collections.asr.models import EncDecCTCModel
SpectrogramGenerator.list_available_models()
Vocoder.list_available_models()
EncDecCTCModel.list_available_models()
```
to get lists.
```py
[PretrainedModelInfo(
 	pretrained_model_name=QuartzNet15x5Base-En,
 	description=QuartzNet15x5 model trained on six datasets: LibriSpeech, Mozilla Common Voice (validated clips from en_1488h_2019-12-10), WSJ, Fisher, Switchboard, and NSC Singapore English. It was trained with Apex/Amp optimization level O1 for 600 epochs. The model achieves a WER of 3.79% on LibriSpeech dev-clean, and a WER of 10.05% on dev-other. Please visit https://ngc.nvidia.com/catalog/models/nvidia:nemospeechmodels for further details.,
 	location=https://api.ngc.nvidia.com/v2/models/nvidia/nemospeechmodels/versions/1.0.0a5/files/QuartzNet15x5Base-En.nemo
 ),
 PretrainedModelInfo(
 	pretrained_model_name=stt_en_quartznet15x5,
 	description=For details about this model, please visit https://ngc.nvidia.com/catalog/models/nvidia:nemo:stt_en_quartznet15x5,
 	location=https://api.ngc.nvidia.com/v2/models/nvidia/nemo/stt_en_quartznet15x5/versions/1.0.0rc1/files/stt_en_quartznet15x5.nemo
 ),
 PretrainedModelInfo(
...
```

**Comment by GeorgeS2019** [comment]
Any suggestion which pair to use? If I understand correctly?

I will read more and come back. Thank you

## German
<details>
<summary><font size=4><strong>For German STT</strong></summary>


https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_de_quartznet15x5

```cs
string modelPath = await DownloadModelAsync("stt_de_quartznet15x5");
```
</details>


#### Todo
- [ ] phonemizers for German
- [ ] tokenizers  for German
> Writing phonemizers/tokenizers for German should not be difficult.
<details>
<summary><font size=4><strong>For German TTS</strong></summary>


# Mel-Spectrogram Generators
<html>
<body>


de-DE | tts_de_fastpitch_multispeaker_5
-- | --



</body>
</html>
<html>
<body>


de-DE | tts_de_fastpitch_singleSpeaker_thorstenNeutral_2102: 21.02
-- | --



</body>
</html>
<html>
<body>


de-DE | tts_de_fastpitch_singleSpeaker_thorstenNeutral_2102: 22.10
-- | --



</body>
</html>

# Vocoders

<html>
<body>


de-DE | tts_de_hui_hifigan_ft_fastpitch_multispeaker_5
-- | --



</body>
</html>
<html>
<body>


de-DE | tts_de_hifigan_singleSpeaker_thorstenNeutral_2102:21.02
-- | --



</body>
</html>
<html>
<body>


de-DE | tts_de_hifigan_singleSpeaker_thorstenNeutral_2210: 22.10
-- | --



</body>
</html>

</details>


## English
<details>
<summary><font size=4><strong>For English STT</strong></summary>

https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_quartznet15x5
```cs
string modelPath = await DownloadModelAsync("stt_en_quartznet15x5");
```
</details>
<details>
<summary><font size=4><strong>For English TTS</strong></summary>

```cs
            string phonemeDict = await DownloadModelAsync("cmudict-0.7b_nv22.10");
            string heteronyms = await DownloadModelAsync("heteronyms-052722");
            string specGenModelPath = await DownloadModelAsync("tts_en_fastpitch");
            string vocoderModelPath = await DownloadModelAsync("tts_en_hifigan");
```
</details>
